#!/bin/sh
ulimit -s 16384
cd /home/glafir/RoR/ic-glafir/
unicorn -c /home/glafir/RoR/ic-glafir/unicorn.rb -E production -D
#unicorn -c /home/glafir/RoR/ic-glafir/unicorn.rb -D
#puma -C /home/glafir/RoR/ic-glafir/puma.rb -d
