#!/bin/sh
railsweb_pid=`cat /home/glafir/RoR/ic-glafir/tmp/pids/unicorn.pid`
#railsweb_pid=`cat /home/glafir/RoR/ic-glafir/tmp/pids/puma.pid`
echo "Stopping RailsWeb ($railsweb_pid)"
kill -9 $railsweb_pid
echo "Unicorn ($railsweb_pid) was stopped!"
